### ISSUE TITLE
Comments on Final

### ISSUE THREAD

**Issue by joseph-hellerstein** [luckystarufo/pySINDy#4]
1. Why are all of the methods in ISINDY static?
2. You have some non-intuitive variable names, like _n in isinidy.py
3. In generator.py, you have a lot of int constants that should be named constants, such as van_der_pol_generator(mu, x_init, dt=0.01, len_t=100):

**Comment by yic317** [comment]
We mean to close this issue, but need to point out that the methods in ISINDY are not all static. Notice ISINDY inherit SINDyBase, thus also inherit methods like coefficients, descriptions, plot_coefficients. These are the only methods we want our users to use; and for int like dt, we meant for our users to choose whichever dt they want to generate the data, that's why we didn't use upper-case letter
