### ISSUE TITLE
Determining Variable Names from Data Array

### ISSUE THREAD

**Issue by kevinegan31** [luckystarufo/pySINDy#8]
When developing array in example 1, is it possible to determine all variable names from that array? I understand that fitting the model provides the variables it deems significant but is it possible to determine all variables corresponding to the derivatives in the data developed by the Van der Pol Generator?

**Comment by luckystarufo** [comment]
I am not sure I understand the question, but I think it's possible. 

The Sindy model only does a sparse regression to your measurements (or state variables, observations, etc. whatever it is called, and in the case of Van der Pol: [https://en.wikipedia.org/wiki/Van_der_Pol_oscillator], they are x and y). However, in example 1, we also expand do a polynomial expansion up to order 3 so that we end up having {1, x, y, xy, x^2y, xy^2, x^3, y^3}.

This is just a framework, you can write your own data generator or try to modify polynomial_expansion() in ./pySINDy/pySINDy/sindybase.py so that you can have your measurements to regress on.
